---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->He thought he saw an Elephant  
That practised on a fife:  
He looked again, and found it was  
A letter from his wife.  
'At length I realize,' he said,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->I have been one acquainted with the night.  
I have walked out in rain - and back in rain.  
I have outwalked the furthest city light.  

I have looked down the saddest city lane.  
I have passed by the watchman on his beat  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->When I go up through the mowing field,  
The headless aftermath,  
Smooth-laid like thatch with the heavy dew,  
Half closes the garden path.  

And when I come to the garden ground,  
The whir of sober birds  
Up from the tangle of withered weeds  
Is sadder than any words  

A tree beside the wall stands bare,  
But a leaf that lingered brown,  
